config/routes.rb
Ads::Application.routes.draw do
 resources :adverts
 resources :users
 resources :sessions, only: [:new, :create, :destroy]
 root to:  "static_page#home"
 match '/signup',  to: 'users#new'
 match '/signin',  to: 'sessions#new'
 match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/advert.rb
# == Schema Information
#
# Table name: adverts
#
#  id          :integer          not null, primary key
#  unit        :string(255)
#  title       :string(255)
#  description :text
#  content     :text
#  draft       :boolean          default(TRUE)
#  archive     :boolean          default(FALSE)
#  admin_ads   :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Advert < ActiveRecord::Base
  attr_accessible :archive, :content, :description, :draft, :title, :unit, :admin_ads
  validates :description, presence: true, length: { maximum: 350 }
  validates :content, presence: true
  validates :title, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
   before_save { |user| user.email = email.downcase }
    before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },  
   uniqueness: { case_sensitive: false }
   validates :password, presence: true, length: { minimum: 6 }
   validates :password_confirmation, presence: true
   
   private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
   before_filter :admin_user,     only: [:destroy, :edit, :update]
  before_filter :signed_in_user, only: [:new, :edit, :update, :create]
  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adverts }
    end
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @advert = Advert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advert }
    end
  end

  # GET /adverts/new
  # GET /adverts/new.json
  def new
    @advert = Advert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advert }
    end
  end

  # GET /adverts/1/edit
  def edit
    @advert = Advert.find(params[:id])
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render json: @advert, status: :created, location: @advert }
      else
        format.html { render action: "new" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adverts/1
  # PUT /adverts/1.json
  def update
    @advert = Advert.find(params[:id])

    respond_to do |format|
      if @advert.update_attributes(params[:advert])
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to adverts_url }
      format.json { head :no_content }
    end
  end
   private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
   include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  end

  def create
      user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
      
    else
        render 'new'
    end
  end

   def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
 before_filter :correct_user, only:  [:edit, :update]
 before_filter :admin_user,     only: [:destroy]
  def index
    @users = User.paginate(page: params[:page])
  end
  def new
	@user = User.new
  end
    def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  def show
   @user = User.find(params[:id])
   
  end
   def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
         sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
   def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end
  
   private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])  
      redirect_to(root_path) unless current_user?(@user) || current_user.admin?
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
      options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
   def current_user?(user)
    user == current_user
  end
  def signed_in?
    !current_user.nil?
  end
   def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/adverts/_form.html.erb
<%= form_for(@advert) do |f| %>
  <% if @advert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advert.errors.count, "error") %> prohibited this advert from being saved:</h2>

      <ul>
      <% @advert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :draft %>
    <%= f.check_box :draft %>
  </div>
  <div class="field">
    <%= f.label :archive %> 
    <%= f.check_box :archive %>
  </div>
  <div class="field">
    <%= f.label :admin_ads %>
    <%= f.check_box :admin_ads %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adverts/edit.html.erb
<h1>Editing advert</h1>

<%= render 'form' %>

<%= link_to 'Show', @advert %> |
<%= link_to 'Back', adverts_path %>

app/views/adverts/index.html.erb
<h1>adverts</h1>

<table>

<% @adverts.each do |advert| %>
  <tr>  <h2><%= advert.title %></h2> </tr>
    
    <tr><p> <%= markdown(advert.description) %> </p></tr>
 

                    <% if current_user && current_user.admin? %>
    <%= link_to 'Правка', edit_advert_path(advert) %> &nbsp
    <%= link_to 'Удалить', advert, method: :delete, data: { confirm: 'Are you sure?' } %> &nbsp
                <% end %>
</table>

<br />
<h4>  <%= link_to 'Подробнее', advert %> </h4>
<% end %>

app/views/adverts/new.html.erb
<h1>New advert</h1>

<%= render 'form' %>

<%= link_to 'Back', adverts_path %>

app/views/adverts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @advert.title %>
</h1>

<p>
  <%= markdown(@advert.content) %>
</p>

 <% if current_user && current_user.admin? %>
<%= link_to 'Править', edit_advert_path(@advert) %> 
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ADS", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Объявления", adverts_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                  <li><%= link_to "Черновик", '#' %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
    
        </ul>
      </nav>
    </div>
  </div>
</header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ads</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
    <div class="container">
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to ADS</h1>
<% if !signed_in? %> 
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
	  <%= gravatar_for user %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %> 
    | <%= link_to "asign admin", '#' %>
     <% end %>    
  <% if current_user.admin? %>
    | <%= link_to "edit", edit_user_path(user) %>
  <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name, "Имя" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "Пароль" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Подтверждение пароля" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Создать пользователя", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  
</div>